### ISSUE TITLE
Dock bar getting duplicated V-20.10 

### ISSUE THREAD

**Issue by DSousa21** [UbuntuDDE/bugs#39]
** Describe the bug **
When you move the cursor over the dock and it goes down, another dock appears...

**Reproduce**
![Screen Capture_select-area_20201113100959](https://user-images.githubusercontent.com/71734707/99076080-57e85500-2599-11eb-904c-958cfcc9c8d4.gif)

**Expected behavior**
Hover the cursor over and the dock bar hide

** Screenshots **
If applicable, add screenshots to help explain your issue.

** Desktop
version 20.10

** Additional context **
Anytime this happens

**Comment by openarun** [comment]
Hi there,
This issue was already fixed and the patch was sent via updates. And can't reproduce it anymore. 
Feel free to reopen if it's an issue again with appropriate steps to reproduce.
Thanks!

**Comment by serial02** [comment]
Hello Ubuntu-DDE Team 20.10

Unfortunately the problem remains. I was unable to record because the screenshot crashed and returns to the tty screen and starts the pc on the screen again after login with all work undone. You can leave it open that as soon as I can reproduce the problem I will expose it here again. The taskbar still continues to overlap.

@openarun 

Edited: As promised, follow image gif showing that the problem exists if it is necessary to reopen this post for analysis and correction. I believe that the Logs sent previously are sufficient to reach an error conclusion for this duplicated dde-dock.

![Screen Capture_dde-desktop_20201208003737](https://user-images.githubusercontent.com/32621790/101436960-f42e1f00-38ed-11eb-971c-078082c55710.gif)

**Comment by serial02** [comment]
Here is another example of how the dde-dock needs to be repaired because it appears in duplicate and does not automatically hide when in "smart hide" mode and does not respond when the browser is fully open.

![Screen Capture_microsoft-edge-dev_20201211180206](https://user-images.githubusercontent.com/32621790/101954980-c4c42e80-3bdb-11eb-84b2-c11be53367f6.gif)

@openarun 
@anantamishra
